export const tabs = [
  { key: 'overview', label: '运行总览', hint: '先关注需要处理的事。' },
  { key: 'video', label: '视频监控', hint: '拖入想看的画面，自由安排你的巡查视图。' },
  { key: 'events', label: '火情事件', hint: '从发现、复核到处理，每个事件都有记录。' },
  { key: 'tasks', label: '任务中心', hint: '从航线规划到任务执行，每次巡护都有完整记录。' },
  { key: 'operations', label: '专业作业', hint: '飞行控制、灭火投送与任务审批。' },
  { key: 'devices', label: '设备管理', hint: '掌握设备状态，查看维护与固件信息。' }
]
export const initialEvents = [
  { id: 'F-0905-003', title: '林缘发现疑似烟点', place: '东区 · 03 号巡护网格', time: '14:32', state: '待复核', level: '优先', device: 1, task: 'T-0905-01', coord: [108.925,34.075], image: 'visible', description: '巡护过程中发现疑似烟点，需要结合现场画面人工核实。', unit: "东区巡护值班组", owner: "值班员", kind: "疑似烟点", timeline: [{"kind": "discover", "title": "发现疑似烟点", "time": "2026-09-05 14:32", "actor": "巡护 01 号", "content": "巡护中发现林缘疑似烟点，可见光现场图片已保存。", "actorLabel": "发现来源"}, {"kind": "notice", "title": "系统提醒", "time": "2026-09-05 14:32", "actor": "东区值班员、网格巡护员", "content": "疑似烟点进入待复核队列，请结合现场图片核实。", "actorLabel": "提醒对象", "contentLabel": "提醒内容"}] },
  { id: 'F-0905-002', title: '农林交界处温度异常', place: '中区 · 07 号巡护网格', time: '14:26', state: '待复核', level: '关注', device: 2, task: 'T-0905-02', coord: [108.85,34.09], image: 'thermal', description: '发现局部热异常，尚未确认真实火情。请先检查证据及现场环境。', unit: "中区巡护值班组", owner: "值班员", kind: "温度异常", timeline: [{"kind": "discover", "title": "发现温度异常", "time": "2026-09-05 14:26", "actor": "巡护 02 号", "content": "农林交界处检测到局部热异常，红外样张已保存。", "actorLabel": "发现来源"}, {"kind": "notice", "title": "系统提醒", "time": "2026-09-05 14:27", "actor": "中区值班员", "content": "热异常暂未确认为火情，请人工核实现场环境。", "actorLabel": "提醒对象", "contentLabel": "提醒内容"}] },
  { id: 'F-0905-001', title: '西区巡护发现疑似明火', place: '西区 · 12 号巡护网格', time: '14:18', state: '待复核', level: '优先', device: 3, task: null, coord: [108.775,34.035], image: 'fire', description: '识别结果仅作为线索，需人工判断现场是否存在明火。', unit: "西区巡护值班组", owner: "值班员", kind: "疑似明火", timeline: [{"kind": "discover", "title": "发现疑似明火", "time": "2026-09-05 14:18", "actor": "巡护 03 号", "content": "西区巡护发现疑似明火，已保存现场识别图片。", "actorLabel": "发现来源"}, {"kind": "notice", "title": "系统提醒", "time": "2026-09-05 14:19", "actor": "西区值班员、网格巡护员", "content": "疑似明火需要优先复核，确认后安排现场核查。", "actorLabel": "提醒对象", "contentLabel": "提醒内容"}] },
  { id: 'F-0905-000', title: '防火通道沿线冒烟', place: '东区 · 05 号巡护网格', time: '13:48', state: '处理中', level: '关注', device: 4, task: 'T-0905-03', coord: [108.965,34.038], image: 'field', description: '已联系现场巡护人员核查，等待处置反馈。', unit: "东区现场巡护组", owner: "东区网格巡护员", kind: "疑似烟点", timeline: [{"kind": "discover", "title": "发现疑似烟点", "time": "2026-09-05 13:48", "actor": "巡护 04 号", "content": "防火通道沿线发现持续冒烟，现场图片已保存。", "actorLabel": "发现来源"}, {"kind": "notice", "title": "系统提醒", "time": "2026-09-05 13:49", "actor": "东区值班员、网格巡护员", "content": "发现疑似烟点，请查看现场证据并组织核查。", "actorLabel": "提醒对象", "contentLabel": "提醒内容"}, {"kind": "review", "title": "人工复核", "time": "2026-09-05 13:54", "actor": "东区值班员", "content": "已查看现场证据并联系网格巡护员。", "result": "转入现场核查"}, {"kind": "dispatch", "title": "关联处置任务", "time": "2026-09-05 14:06", "actor": "东区值班员", "content": "已关联防火通道现场核查任务 T-0905-03。", "result": "任务待执行，等待现场确认"}] },
  { id: 'F-0904-006', title: '道路施工扬尘', place: '中区 · 06 号巡护网格', time: '昨日 16:10', state: '已排除', level: '一般', device: 5, task: null, coord: [108.9,34.14], image: 'field', description: '现场核查为道路施工扬尘，已排除火情。', unit: "中区现场巡护组", owner: "中区网格巡护员", kind: "施工扬尘", timeline: [{"kind": "discover", "title": "发现疑似烟雾", "time": "2026-09-04 16:10", "actor": "巡护 05 号", "content": "道路附近出现疑似烟雾，事件进入复核队列。", "actorLabel": "发现来源"}, {"kind": "review", "title": "现场核查", "time": "2026-09-04 16:21", "actor": "中区网格巡护员", "content": "已核查现场，烟雾为道路施工产生的扬尘。", "result": "未发现明火或燃烧迹象"}, {"kind": "done", "title": "排除火情", "time": "2026-09-04 16:24", "actor": "中区值班员", "content": "结合现场反馈，确认属于施工扬尘。", "result": "已排除，事件关闭"}] },
  { id: 'F-0904-005', title: '林缘热源复查', place: '西区 · 10 号巡护网格', time: '昨日 11:35', state: '已结束', level: '一般', device: 6, task: 'T-0904-06', coord: [108.76,34.11], image: 'thermal', description: '现场复查完成，相关证据已归档。', unit: "西区现场巡护组", owner: "西区网格巡护员", kind: "热源复查", timeline: [{"kind": "discover", "title": "建立核查事件", "time": "2026-09-04 11:35", "actor": "巡护 06 号", "content": "林缘发现热源，已建立重点复查事件。", "actorLabel": "发现来源"}, {"kind": "dispatch", "title": "安排现场复查", "time": "2026-09-04 11:42", "actor": "西区值班员", "content": "已关联西区热源复查任务 T-0904-06，巡护员开展核查。"}, {"kind": "feedback", "title": "现场反馈", "time": "2026-09-04 12:02", "actor": "西区网格巡护员", "content": "热源复查完成，现场未见持续烟火。", "result": "已补充核查记录"}, {"kind": "done", "title": "处置完成", "time": "2026-09-04 12:08", "actor": "西区值班员", "content": "复查结果已确认，相关任务及证据已归档。", "result": "已结束"}] },
]
export const initialTasks = [
  { id: 'T-0905-01', routeId: 'R-001', name: '东区林缘日常巡护', kind: '日常巡检', state: '执行中', progress: 68, device: 1, event: 'F-0905-003', start: '14:08', duration: '24 分钟', points: '17 / 25', note: '按计划巡护，发现 1 条待复核线索。' },
  { id: 'T-0905-02', routeId: 'R-002', name: '中区重点网格复查', kind: '重点复查', state: '执行中', progress: 42, device: 2, event: 'F-0905-002', start: '14:15', duration: '17 分钟', points: '8 / 19', note: '核查热异常区域，等待人工复核。' },
  { id: 'T-0905-03', name: '防火通道现场核查', kind: '事件处置', state: '待执行', progress: 0, device: 4, event: 'F-0905-000', start: '待安排', duration: '—', points: '0 / 12', note: '等待现场人员确认执行条件。' },
  { id: 'T-0904-06', routeId: 'R-003', name: '西区热源复查', kind: '重点复查', state: '已完成', progress: 100, device: 6, event: 'F-0904-005', start: '昨日 11:35', duration: '33 分钟', points: '20 / 20', note: '复查完成，已保存航迹与核查记录。' }
]
export const devices = Array.from({ length: 20 }, (_, i) => ({
  id: i + 1, name: `巡护 ${String(i + 1).padStart(2, '0')} 号`, model: i % 3 === 0 ? 'M300 RTK' : i % 3 === 1 ? 'M350 RTK' : 'Matrice 4T',
  sn: `DEMO-AIRCRAFT-${String(i + 1).padStart(2, '0')}`, battery: i === 6 ? 22 : 86 - (i * 3 % 39),
  state: i === 6 ? '低电量' : i === 11 ? '视频弱网' : i < 4 ? '巡护中' : '待命',
  quality: i < 4 ? '高清' : '低清', channel: i === 11 ? '弱网' : '正常',
  image: ['visible', 'thermal', 'field', 'visible'][i % 4], coord: [108.78 + (i % 5) * 0.049, 34.025 + Math.floor(i / 5) * 0.039]
}))
