<template><section><nav class="work-subnav" aria-label="平台管理功能"><a v-for="item in sections" :href="`#management/${item.key}`" :class="{active:area===item.key}" @click="area=item.key"><component :is="item.icon" />{{ item.label }}</a></nav>
<template v-if="area==='media'"><div class="work-intro"><div><h2>媒体资料</h2><p>按任务归集照片、红外证据和现场资料。</p></div><label class="search-field"><SearchOutlined /><input v-model="search" placeholder="搜索资料或事件" aria-label="搜索媒体资料" /></label></div><div class="media-library"><button v-for="event in filteredMedia" class="panel media-card" @click="media=event;preview.showModal()"><div><img :src="photo(event.image)" :alt="event.title" /><span>历史样张</span></div><h3>{{ event.title }}</h3><p>{{ event.id }} · {{ event.time }}</p><footer>{{ event.place }}<PictureOutlined /></footer></button><div v-if="!filteredMedia.length" class="panel empty">未找到匹配资料<button class="text-button" @click="search=''">清除筛选</button></div></div></template>
<template v-else-if="area==='maintenance'||area==='firmware'"><div class="work-intro"><div><h2>{{ area==='maintenance'?'设备维护':'固件管理' }}</h2><p>{{ area==='maintenance'?'查看设备检查项和维护记录，回到设备台账查看完整状态。':'集中核对版本与升级条件，保留设备维护入口。' }}</p></div><button class="button secondary" @click="$emit('devices')">返回设备台账</button></div><div class="panel table-panel"><table><thead><tr><th>设备</th><th>型号</th><th>{{ area==='maintenance'?'检查项':'登记版本' }}</th><th>状态</th><th>最近记录</th><th>操作</th></tr></thead><tbody><tr v-for="device in devices.slice(0,8)"><td>{{ device.name }}</td><td>{{ device.model }}</td><td>{{ area==='maintenance'?'电池 / 链路 / 云台':'版本待设备核对' }}</td><td><span class="status" :class="checked.includes(device.id)?'success':'neutral'">{{ checked.includes(device.id)?'已记录检查':'待检查' }}</span></td><td>{{ checked.includes(device.id)?'本次演示已记录':'今日 08:30' }}</td><td><button class="text-button" @click="checked.includes(device.id)||checked.push(device.id);$emit('notify','检查流程已记录，仅更新本次演示')">{{ area==='maintenance'?'记录检查':'模拟核对版本' }}</button></td></tr></tbody></table></div><p class="notice-inline work-space-top">此处展示管理流程；不安装固件、不修改真实设备设置。</p></template>
<template v-else-if="area==='members'"><div class="work-intro"><div><h2>成员与权限</h2><p>按职责组织查看、规划、复核与专业作业权限。</p></div></div><div class="panel table-panel"><table><thead><tr><th>成员</th><th>所属单位</th><th>角色</th><th>权限范围</th><th>操作</th></tr></thead><tbody><tr v-for="person in members"><td>{{ person.name }}</td><td>{{ person.unit }}</td><td>{{ person.role }}</td><td>{{ scopes[person.role] }}</td><td><button class="text-button" @click="member=person;memberRole=person.role;memberDialog.showModal()">调整演示角色</button></td></tr></tbody></table></div></template>
<template v-else><div class="work-intro"><div><h2>地图与空域</h2><p>地图图层和空域资料集中管理，规划时查看对应约束。</p></div><button class="button primary" @click="$emit('planner')">进入航线规划</button></div><div class="operations-grid"><div class="panel management-map"><PatrolMap :events="events" :devices="devices" @select-event="$emit('event',$event)" /></div><aside class="panel"><div class="work-panel-heading"><h2>图层与区域资料</h2></div><div class="work-form"><div class="management-layer" v-for="layer in layers"><div><strong>{{ layer.name }}</strong><p>{{ layer.note }}</p></div><span class="status neutral">{{ layer.status }}</span></div><p class="notice-inline">预览底图与点位均用于演示。实际空域约束继续由正式规划与飞行检查流程提供。</p></div></aside></div></template>
<dialog ref="preview" class="work-dialog media-dialog" aria-label="媒体资料预览"><header><h2>{{ media?.title }}</h2><button class="icon-button" aria-label="关闭资料预览" @click="preview.close()"><CloseOutlined /></button></header><img v-if="media" :src="photo(media.image)" :alt="media.title" /><footer><span>历史样张 · {{ media?.id }}</span><button class="button primary" @click="preview.close();$emit('event',media)">查看关联事件</button></footer></dialog>
<dialog ref="memberDialog" class="work-dialog" aria-label="调整演示角色"><form @submit.prevent="member.role=memberRole;memberDialog.close();$emit('notify','演示角色已更新，真实权限未变更')"><header><h2>{{ member?.name }} · 演示角色</h2><button type="button" class="icon-button" aria-label="关闭角色设置" @click="memberDialog.close()"><CloseOutlined /></button></header><label class="work-form">角色<select v-model="memberRole" aria-label="角色"><option v-for="(_,role) in scopes">{{ role }}</option></select></label><p class="notice-inline">{{ scopes[memberRole] }}</p><footer><button class="button primary">保存演示设置</button></footer></form></dialog>
</section></template>
<script setup>
import {ref,computed,onMounted,onBeforeUnmount} from 'vue'
import {PictureOutlined,ToolOutlined,CloudUploadOutlined,TeamOutlined,EnvironmentOutlined,SearchOutlined,CloseOutlined} from '@ant-design/icons-vue'
import PatrolMap from './PatrolMap.vue'
const props=defineProps({events:Array,devices:Array});defineEmits(['notify','devices','planner','event'])
const sections=[{key:'media',label:'媒体资料',icon:PictureOutlined},{key:'maintenance',label:'设备维护',icon:ToolOutlined},{key:'firmware',label:'固件管理',icon:CloudUploadOutlined},{key:'members',label:'成员权限',icon:TeamOutlined},{key:'map',label:'地图与空域',icon:EnvironmentOutlined}]
const area=ref('media'),search=ref(''),checked=ref([]),media=ref(null),preview=ref(null),member=ref(null),memberRole=ref('值班员'),memberDialog=ref(null)
const scopes={'值班员':'查看态势、事件复核、任务跟踪','航线规划员':'航线编辑、任务创建、执行记录','观察员':'查看态势、视频、事件和任务'}
const members=ref([{name:'东区值班员',unit:'东区巡护组',role:'值班员'},{name:'巡护规划员',unit:'巡护保障组',role:'航线规划员'},{name:'指挥中心观察员',unit:'指挥中心',role:'观察员'}])
const layers=[{name:'基础地图',note:'OpenStreetMap 预览底图',status:'已显示'},{name:'事件与飞机',note:'示例事件及巡护飞机点位',status:'已显示'},{name:'空域与限制区',note:'正式空域文件、审批和限制区域入口',status:'待导入正式数据'}]
const filteredMedia=computed(()=>props.events.filter(e=>(e.title+e.id).includes(search.value.trim())))
const photo=key=>new URL(`./assets/${key}.jpg`,import.meta.url).href
function sync(){const key=location.hash.split('/')[1];area.value=sections.some(s=>s.key===key)?key:'media'}
onMounted(()=>{sync();window.addEventListener('hashchange',sync)});onBeforeUnmount(()=>window.removeEventListener('hashchange',sync))
</script>
