<template><section><nav class="work-subnav" aria-label="专业作业功能"><a v-for="item in sections" :href="`#operations/${item.key}`" :class="{active:area===item.key}" @click="area=item.key"><component :is="item.icon" />{{ item.label }}</a></nav>
  <template v-if="area==='flight'"><div class="work-intro"><div><h2>飞行控制工作台</h2><p>集中查看飞机、现场画面与控制状态。</p></div><label class="work-inline-label">当前飞机<select v-model.number="deviceId"><option v-for="d in devices" :value="d.id">{{ d.name }} · {{ d.model }}</option></select></label></div><div class="operations-grid"><article class="panel operations-visual"><PatrolMap :devices="[device]" :events="events" @select-event="$emit('event',$event)" /><div class="operations-camera"><img :src="photo(lens==='红外'?'thermal':device.image)" alt="飞行工作台历史样张" :style="{transform:`scale(${1+(Number(zoom)-1)*.1})`}" /><span>历史样张 · 非实时</span><div class="segmented"><button v-for="item in ['可见光','红外']" :class="{active:lens===item}" @click="lens=item">{{ item }}</button></div></div></article><aside class="panel operations-console"><div class="work-panel-heading"><h2>{{ device.name }}</h2><span class="status info">{{ flightState }}</span></div><div class="work-metrics two"><div><span>电量</span><strong>{{ device.battery }}%</strong></div><div><span>相对高度</span><strong>100 <small>m</small></strong></div><div><span>飞行速度</span><strong>8 <small>m/s</small></strong></div><div><span>控制状态</span><strong>{{ control?'已接管演示':'仅观察' }}</strong></div></div><div class="work-form"><h3>云台与镜头</h3><label>俯仰角 {{ pitch }}°<input type="range" v-model="pitch" min="-90" max="30" aria-label="云台俯仰角" /></label><label>画面倍率 {{ zoom }}×<input type="range" v-model="zoom" min="1" max="10" aria-label="画面倍率" /></label><button class="button secondary" @click="pitch=-45;zoom=1;$emit('notify','云台演示参数已复位')">云台复位</button><h3>飞行操作</h3><button class="button primary" @click="control=!control">{{ control?'释放演示控制权':'申请演示控制权' }}</button><div class="work-actions"><button class="button secondary" :disabled="!control" @click="flightState='悬停演示';$emit('notify','演示已切换为悬停状态')">模拟悬停</button><button class="button secondary" :disabled="!control" @click="flightState='返航演示';$emit('notify','演示已切换为返航状态')">模拟返航</button></div><p class="notice-inline">本页仅演示布局和状态切换，不向飞机发送指令。</p><button class="text-button" @click="$emit('video',deviceId)">打开多画面监控 <ArrowRightOutlined /></button></div></aside></div></template>
  <template v-else-if="area==='delivery'"><div class="work-intro"><div><h2>灭火与投送任务</h2><p>从事件、任务审批到执行反馈，保留专业作业流程。</p></div><button class="button secondary" @click="setArea('approvals')"><SafetyCertificateOutlined />查看审批记录</button></div><div class="work-flow-steps"><div v-for="(label,index) in ['关联火情','准备资源','任务审批','执行与反馈']" :class="{active:index===step,done:index<step}"><b>{{ index+1 }}</b><span>{{ label }}</span></div></div><div class="operations-grid"><article class="panel"><div class="work-panel-heading"><div><span class="eyebrow">投送任务 / D-DEMO-001</span><h2>防火通道火情处置</h2></div><span class="status" :class="deliveryState==='已完成'?'success':'info'">{{ deliveryState }}</span></div><div class="delivery-preview"><PlanningMap :points="deliveryPoints" title="投送航线示例" /></div><div class="work-metrics"><div><span>投送设备</span><strong>FC100 · 01 号</strong></div><div><span>任务航点</span><strong>4 <small>个</small></strong></div><div><span>预计里程</span><strong>3.6 <small>km</small></strong></div><div><span>关联事件</span><button class="text-button" @click="$emit('event',events.find(e=>e.id==='F-0905-000')||events[0])">查看火情 <ArrowRightOutlined /></button></div></div></article><aside class="panel"><div class="work-panel-heading"><h2>任务准备与审批</h2></div><div class="work-form"><label>任务类型<select v-model="deliveryType" :disabled="step>=2"><option>灭火投送</option><option>物资投送</option></select></label><label>载荷配置<input v-model="payload" :disabled="step>=2" aria-label="载荷配置" /></label><label>审批说明<textarea v-model="approvalNote" :disabled="step>=2" rows="3" placeholder="填写任务说明和现场条件" /></label><label class="work-check"><input v-model="prepared" type="checkbox" :disabled="step>=2" />已核对示例航线与资源信息</label><div class="notice-inline">这是业务流程演示；真实作业仍需完成飞行条件检查与授权。</div><button v-if="step<2" class="button primary" :disabled="!prepared||!approvalNote.trim()||!payload.trim()" @click="step=2;deliveryState='待审批';approvalStatus='待审批';setArea('approvals')">提交演示审批</button><button v-if="deliveryState==='待执行'" class="button primary" @click="step=3;deliveryState='执行中';$emit('notify','示例任务进入执行中')">模拟启动任务</button><button v-if="deliveryState==='执行中'" class="button primary" @click="deliveryState='已完成';$emit('notify','示例任务完成，处置结果已留存')">模拟完成并反馈</button><p v-if="deliveryState==='已完成'" class="notice-inline"><CheckCircleOutlined />本次示例处置完成，记录已保留。</p></div></aside></div></template>
  <template v-else><div class="work-intro"><div><h2>任务审批</h2><p>区分待审批、已通过与退回，处理后回到任务继续查看。</p></div><button class="button secondary" @click="setArea('delivery')">返回投送任务</button></div><div class="panel table-panel"><table><thead><tr><th>任务</th><th>类型</th><th>申请人</th><th>说明</th><th>审批状态</th><th>操作</th></tr></thead><tbody><tr><td>防火通道火情处置<small class="work-cell-sub">D-DEMO-001</small></td><td>{{ deliveryType }}</td><td>东区值班员</td><td>{{ approvalNote||'任务准备中' }}</td><td><span class="status" :class="approvalStatus==='已通过'?'success':'warn'">{{ approvalStatus }}</span></td><td><div class="work-actions"><button v-if="approvalStatus==='待审批'" class="text-button" @click="approvalStatus='已通过';deliveryState='待执行';$emit('notify','演示审批通过，任务可模拟执行')">通过审批</button><button v-if="approvalStatus==='待审批'" class="text-button" @click="approvalStatus='已退回';deliveryState='待完善';step=1;$emit('notify','已退回，可完善任务后再次提交')">退回完善</button><button class="text-button" @click="setArea('delivery')">任务详情</button></div></td></tr><tr><td>西区热源复查<small class="work-cell-sub">D-DEMO-000</small></td><td>现场核查</td><td>西区值班员</td><td>历史核查任务</td><td><span class="status success">已通过</span></td><td><button class="text-button" @click="$emit('task','T-0904-06')">查看记录</button></td></tr></tbody></table></div></template>
</section></template>
<script setup>
import {ref,computed,toRefs,watch,onMounted,onBeforeUnmount} from 'vue'
import {ControlOutlined,SendOutlined,SafetyCertificateOutlined,ArrowRightOutlined,CheckCircleOutlined} from '@ant-design/icons-vue'
import { operations } from './operations-state'
import PatrolMap from './PatrolMap.vue'
import PlanningMap from './PlanningMap.vue'
const props=defineProps({devices:Array,events:Array});defineEmits(['notify','video','event','task'])
const sections=[{key:'flight',label:'飞行控制',icon:ControlOutlined},{key:'delivery',label:'灭火与投送',icon:SendOutlined},{key:'approvals',label:'任务审批',icon:SafetyCertificateOutlined}]
const area=ref('flight'),deviceId=ref(1),lens=ref('可见光'),control=ref(false),pitch=ref(-45),zoom=ref(1),flightState=ref('巡护中')
const {step,deliveryState,approvalStatus,approvalNote,payload,prepared,deliveryType}=toRefs(operations)
const device=computed(()=>props.devices.find(d=>d.id===deviceId.value)||props.devices[0]);const photo=key=>new URL(`./assets/${key}.jpg`,import.meta.url).href
const deliveryPoints=[{lng:108.84,lat:34.08},{lng:108.855,lat:34.085},{lng:108.87,lat:34.09},{lng:108.875,lat:34.095}]
watch(deviceId,()=>{control.value=false;flightState.value=device.value.state;pitch.value=-45;zoom.value=1})
function sync(){const key=location.hash.split('/')[1];area.value=sections.some(s=>s.key===key)?key:'flight'}
function setArea(key){area.value=key;location.hash=`operations/${key}`}
onMounted(()=>{sync();window.addEventListener('hashchange',sync)});onBeforeUnmount(()=>window.removeEventListener('hashchange',sync))
</script>
