<template>
  <section class="task-center">
    <nav class="work-subnav" aria-label="任务中心功能"><a v-for="item in areas" :key="item.key" :href="`#tasks/${item.key}`" :class="{active:area===item.key}" @click="area=item.key"><component :is="item.icon" />{{ item.label }}<span v-if="item.key==='routes'">{{ planning.routes.length }}</span></a></nav>
    <template v-if="area==='routes'">
      <div class="work-intro"><div><h2>航线库</h2><p>规划一次，多次执行。每次飞行单独留存任务和执行记录。</p></div><div class="work-actions"><button class="button secondary" @click="importDialog.showModal()"><ImportOutlined />导入航线</button><button class="button primary" @click="editRoute(null)"><PlusOutlined />新建航线</button></div></div>
      <div class="route-library-grid">
        <aside class="route-library-list"><label class="search-field"><SearchOutlined /><input v-model="search" aria-label="搜索航线" placeholder="搜索航线名称或区域" /></label><div class="route-library-scroll"><button v-for="route in filteredRoutes" :key="route.id" class="route-library-card panel" :class="{selected:selectedRoute.id===route.id}" @click="planning.selectedRouteId=route.id"><div><span class="small-tag">{{ route.model }}</span><small>{{ route.id }}</small></div><h3>{{ route.name }}</h3><p>{{ route.area }}</p><div class="route-library-metrics"><span>{{ route.points.length }} 航点</span><span>{{ route.height }} m</span><span>{{ route.speed }} m/s</span></div><footer><span>{{ route.updated }}更新</span><span>已执行 {{ route.uses }} 次</span></footer></button><div v-if="!filteredRoutes.length" class="panel empty">没有匹配的航线<button class="text-button" @click="search=''">清除搜索</button></div></div></aside>
        <article class="panel route-library-detail"><header class="work-panel-heading"><div><span class="eyebrow">航线预览 / {{ selectedRoute.id }}</span><h2>{{ selectedRoute.name }}</h2></div><span class="status success">可复用</span></header><PlanningMap :key="selectedRoute.id" :points="selectedRoute.points" :title="selectedRoute.area" /><div class="work-metrics"><div><span>航线里程</span><strong>{{ routeDistance(selectedRoute.points).toFixed(1) }} <small>km</small></strong></div><div><span>预计飞行</span><strong>{{ estimated(selectedRoute) }} <small>分钟</small></strong></div><div><span>完成动作</span><strong>{{ selectedRoute.finish }}</strong></div><div><span>适用机型</span><strong>{{ selectedRoute.model }}</strong></div></div><footer class="work-panel-footer"><span>航线与执行记录分别管理</span><div class="work-actions"><button class="button secondary" @click="editRoute(selectedRoute)"><EditOutlined />编辑航线</button><button class="button primary" @click="prepareTask(selectedRoute)"><SendOutlined />创建巡检任务</button></div></footer></article>
      </div>
    </template>
    <template v-else-if="area==='planner'">
      <div class="work-intro"><div><h2>{{ draft.name || '新建巡护航线' }}</h2><p>在地图添加航点，设置航高和动作，保存后可创建巡检任务。</p></div><div class="work-actions"><button class="button secondary" @click="setArea('routes')">返回航线库</button><button class="button primary" :disabled="!validDraft" @click="saveRoute"><SaveOutlined />保存航线</button></div></div>
      <div class="planner-workspace">
        <aside class="panel planner-settings"><div class="work-panel-heading"><h2>航线设置</h2><span class="small-tag">{{ draft.points.length }} 航点</span></div><div class="work-form"><label>航线名称<input v-model="draft.name" maxlength="40" aria-label="航线名称" /></label><label>所属区域<input v-model="draft.area" aria-label="所属区域" /></label><label>适用机型<select v-model="draft.model" aria-label="适用机型"><option>M300 RTK</option><option>M350 RTK</option><option>Matrice 4T</option></select></label><div class="work-form-pair"><label>航线高度 · m<input v-model.number="draft.height" type="number" min="20" max="500" aria-label="航线高度" /></label><label>飞行速度 · m/s<input v-model.number="draft.speed" type="number" min="1" max="15" aria-label="飞行速度" /></label></div><label>完成动作<select v-model="draft.finish"><option>返航</option><option>悬停</option></select></label><button class="text-button" @click="draft.points.forEach(p=>p.height=draft.height)">将航线高度应用到全部航点</button><p class="work-muted">高度相对起飞点；参数仅用于本次演示。</p></div><div class="planner-summary"><span>预计里程 <strong>{{ routeDistance(draft.points).toFixed(1) }} km</strong></span><span>预计飞行 <strong>{{ estimated(draft) }} 分钟</strong></span></div></aside>
        <div class="planner-map-column"><div class="planner-tools"><button class="button" :class="drawing?'primary':'secondary'" @click="drawing=!drawing"><PlusOutlined />{{ drawing?'正在添加航点':'添加航点' }}</button><button class="button secondary" :disabled="!draft.points.length" @click="removePoint(draft.points.length-1)"><UndoOutlined />撤销末点</button><span>{{ draft.points.length }} 个航点</span></div><PlanningMap :key="draft.id" :points="draft.points" :selected="pointIndex" editable :drawing="drawing" :title="draft.name" @add="addPoint" @select="pointIndex=$event" /></div>
        <aside class="panel planner-points"><div class="work-panel-heading"><h2>航点与动作</h2><button class="text-button" @click="addPoint()"><PlusOutlined />添加</button></div><div class="planner-point-list"><button v-for="(point,index) in draft.points" :key="index" :class="{active:pointIndex===index}" @click="pointIndex=index"><b>{{ String(index+1).padStart(2,'0') }}</b><span>航点 {{ index+1 }}<small>{{ point.height }} m · {{ point.action }}</small></span><RightOutlined /></button><p v-if="!draft.points.length" class="empty">点击地图或“添加”设置第一个航点</p></div><div v-if="activePoint" class="work-form waypoint-form"><h3>航点 {{ pointIndex+1 }} 参数</h3><label>经度<input v-model.number="activePoint.lng" type="number" step="0.000001" min="-180" max="180" aria-label="航点经度" /></label><label>纬度<input v-model.number="activePoint.lat" type="number" step="0.000001" min="-85" max="85" aria-label="航点纬度" /></label><div class="work-form-pair"><label>高度 · m<input v-model.number="activePoint.height" type="number" min="20" max="500" aria-label="航点高度" /></label><label>航点动作<select v-model="activePoint.action"><option>拍照</option><option>悬停观察</option><option>无动作</option></select></label></div><button class="text-button work-danger" @click="removePoint(pointIndex)"><DeleteOutlined />删除当前航点</button></div></aside>
      </div><p v-if="!validDraft" class="work-validation">请填写名称与区域，至少设置 2 个有效航点；高度 20–500 m，速度 1–15 m/s。</p>
    </template>
    <template v-else-if="area==='missions'||area==='history'">
      <div class="work-intro"><div><h2>{{ area==='history'?'历史执行记录':'巡检任务' }}</h2><p>{{ area==='history'?'保留每次执行结果，同一条航线可以再次创建任务。':'选择航线和执行飞机，安排时间并跟踪任务进度。' }}</p></div><button class="button primary" @click="prepareTask(selectedRoute)"><PlusOutlined />创建巡检任务</button></div>
      <div class="work-table-controls"><div class="segmented" v-if="area==='missions'"><button v-for="state in ['全部','待执行','执行中','已暂停']" :class="{active:missionFilter===state}" @click="missionFilter=state">{{ state }}</button></div><span class="work-muted">共 {{ shownTasks.length }} 条{{ area==='history'?'执行记录':'任务' }}</span></div>
      <div class="panel table-panel"><table><thead><tr><th>任务名称 / 编号</th><th>巡护航线</th><th>执行飞机</th><th>计划时间</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="task in shownTasks" :key="task.id"><td><strong>{{ task.name }}</strong><small class="work-cell-sub">{{ task.id }}</small></td><td>{{ task.routeName||task.name }}</td><td>{{ deviceName(task.device) }}</td><td>{{ task.schedule||task.start }}</td><td><span class="status" :class="task.state==='已完成'?'success':task.state==='待执行'?'warn':'info'">{{ task.state }}</span></td><td><div class="work-actions"><button class="text-button" @click="viewTask(task)">查看{{ area==='history'?'记录':'任务' }}</button><button v-if="task.state==='待执行'" class="text-button" @click="$emit('action',{task,action:'start'});viewTask(task)">模拟下发</button><button v-if="task.state==='已完成'" class="text-button" @click="repeatTask(task)">再次执行</button></div></td></tr></tbody></table><div v-if="!shownTasks.length" class="empty">暂无此类任务</div></div>
    </template>
    <template v-else><div class="work-intro"><div><h2>执行监控</h2><p>查看航点进度、现场画面与关联事件。</p></div><div class="work-actions" v-if="selectedTask"><button v-if="selectedTask.state==='待执行'" class="button primary" @click="$emit('action',{task:selectedTask,action:'start'})">模拟下发</button><button v-if="selectedTask.state==='执行中'" class="button secondary" @click="$emit('action',{task:selectedTask,action:'pause'})"><PauseCircleOutlined />暂停演示</button><button v-if="selectedTask.state==='已暂停'" class="button primary" @click="$emit('action',{task:selectedTask,action:'resume'})">继续演示</button><button v-if="['执行中','已暂停'].includes(selectedTask.state)" class="button secondary" @click="$emit('action',{task:selectedTask,action:'finish'})"><CheckCircleOutlined />模拟完成</button><button v-if="selectedTask.state==='已完成'" class="button primary" @click="repeatTask(selectedTask)">再次执行</button></div></div><slot name="execution" /></template>
    <dialog ref="taskDialog" class="work-dialog" aria-label="创建巡检任务"><form @submit.prevent="createTask"><header><div><span class="eyebrow">任务中心</span><h2>{{ repeatSource?'再次执行 · 新建任务':'创建巡检任务' }}</h2></div><button type="button" class="icon-button" aria-label="关闭创建任务" @click="taskDialog.close()"><CloseOutlined /></button></header><div class="work-form"><label>任务名称<input v-model="taskForm.name" required maxlength="60" aria-label="任务名称" /></label><label>巡护航线<select v-model="taskForm.routeId" aria-label="巡护航线" @change="alignDevice"><option v-for="route in planning.routes" :value="route.id">{{ route.name }}</option></select></label><label>执行飞机<select v-model.number="taskForm.device" required aria-label="执行飞机"><option v-for="device in compatibleDevices" :value="device.id">{{ device.name }} · {{ device.model }}</option></select></label><label>执行方式<select v-model="taskForm.mode" aria-label="执行方式"><option>立即执行</option><option>定时执行</option></select></label><label v-if="taskForm.mode==='定时执行'">计划时间<input v-model="taskForm.schedule" type="datetime-local" required aria-label="计划时间" /></label><p class="notice-inline">保存为待执行任务；“模拟下发”仅推进演示状态。每次执行有独立编号，原记录保持保留。</p></div><footer><button type="button" class="button secondary" @click="taskDialog.close()">取消</button><button class="button primary" :disabled="!compatibleDevices.length">保存任务</button></footer></form></dialog>
    <dialog ref="importDialog" class="work-dialog" aria-label="导入航线"><header><h2>导入航线</h2><button class="icon-button" aria-label="关闭导入航线" @click="importDialog.close()"><CloseOutlined /></button></header><p>正式航线库保留 KMZ 导入入口。本原型提供示例导入流程，检查航点与机型后再保存。</p><div class="import-sample"><FileOutlined /><div><strong>北区巡护示例.kmz</strong><small>6 个航点 · M300 RTK · 相对起飞点高度 100 m</small></div><span class="status success">示例文件</span></div><button class="button primary wide" @click="importSample">加载示例并检查航线</button></dialog>
  </section>
</template>
<script setup>
import {ref,computed,onMounted,onBeforeUnmount} from 'vue'
import {ApartmentOutlined,EnvironmentOutlined,ScheduleOutlined,PlayCircleOutlined,HistoryOutlined,PlusOutlined,SearchOutlined,EditOutlined,SendOutlined,SaveOutlined,UndoOutlined,DeleteOutlined,RightOutlined,CloseOutlined,CheckCircleOutlined,PauseCircleOutlined,ImportOutlined,FileOutlined} from '@ant-design/icons-vue'
import PlanningMap from './PlanningMap.vue'
import {planning,routeDistance,initialRoutes} from './planning-data'
const props=defineProps({tasks:Array,devices:Array,selectedTask:Object})
const emit=defineEmits(['select','create','action','notify'])
const areas=[{key:'routes',label:'航线库',icon:ApartmentOutlined},{key:'planner',label:'航线规划',icon:EnvironmentOutlined},{key:'missions',label:'巡检任务',icon:ScheduleOutlined},{key:'monitor',label:'执行监控',icon:PlayCircleOutlined},{key:'history',label:'历史记录',icon:HistoryOutlined}]
const area=ref('routes'),search=ref(''),missionFilter=ref('全部'),pointIndex=ref(0),drawing=ref(false),taskDialog=ref(null),importDialog=ref(null),repeatSource=ref(null)
const selectedRoute=computed(()=>planning.routes.find(r=>r.id===planning.selectedRouteId)||planning.routes[0])
if(!planning.draft)planning.draft=structuredClone(initialRoutes[0])
const draft=computed(()=>planning.draft)
const activePoint=computed(()=>draft.value.points[pointIndex.value])
const filteredRoutes=computed(()=>planning.routes.filter(r=>(r.name+r.area+r.model).includes(search.value.trim())))
const validDraft=computed(()=>draft.value.name.trim()&&draft.value.area.trim()&&draft.value.height>=20&&draft.value.height<=500&&draft.value.speed>=1&&draft.value.speed<=15&&draft.value.points.length>=2&&draft.value.points.every(p=>Number.isFinite(p.lng)&&Number.isFinite(p.lat)&&Math.abs(p.lng)<=180&&Math.abs(p.lat)<=85&&p.height>=20&&p.height<=500))
const shownTasks=computed(()=>props.tasks.filter(t=>area.value==='history'?t.state==='已完成':missionFilter.value==='全部'||t.state===missionFilter.value))
const taskForm=ref({name:'',routeId:'R-001',device:1,mode:'立即执行',schedule:'2026-09-06T09:00'})
const formRoute=computed(()=>planning.routes.find(r=>r.id===taskForm.value.routeId)||selectedRoute.value)
const compatibleDevices=computed(()=>props.devices.filter(d=>d.model===formRoute.value.model))
const deviceName=id=>props.devices.find(d=>d.id===id)?.name||'未分配'
const copy=x=>JSON.parse(JSON.stringify(x))
function sync(){const key=location.hash.split('/')[1];area.value=areas.some(a=>a.key===key)?key:key?.startsWith('T-')?'monitor':'routes'}
function setArea(key){area.value=key;location.hash=`tasks/${key}`}
function estimated(route){return Math.max(1,Math.ceil(routeDistance(route.points)*1000/(route.speed||8)/60))}
function editRoute(route){planning.draft=route?copy(route):{id:`R-${Date.now()}`,name:'新建巡护航线',area:'东区 · 新规划区域',model:'M300 RTK',height:100,speed:8,finish:'返航',image:'visible',updated:'刚刚',uses:0,points:[]};pointIndex.value=0;drawing.value=!route;setArea('planner')}
function addPoint(point){const last=draft.value.points.at(-1);draft.value.points.push({...(point||{lng:+((last?.lng||108.82)+.005).toFixed(6),lat:+((last?.lat||34.07)+.003).toFixed(6)}),height:draft.value.height,action:'拍照'});pointIndex.value=draft.value.points.length-1}
function removePoint(index){draft.value.points.splice(index,1);pointIndex.value=Math.min(pointIndex.value,Math.max(0,draft.value.points.length-1))}
function saveRoute(){if(!validDraft.value)return;const route={...copy(draft.value),updated:'刚刚'};const index=planning.routes.findIndex(r=>r.id===route.id);if(index>=0)planning.routes.splice(index,1,route);else planning.routes.push(route);planning.selectedRouteId=route.id;setArea('routes');emit('notify','航线已保存，可继续创建巡检任务')}
function alignDevice(){taskForm.value.device=compatibleDevices.value[0]?.id||0}
function prepareTask(route){repeatSource.value=null;taskForm.value={name:route.name,routeId:route.id,device:props.devices.find(d=>d.model===route.model)?.id||0,mode:'立即执行',schedule:'2026-09-06T09:00'};taskDialog.value.showModal()}
function repeatTask(task){let route=planning.routes.find(r=>r.id===task.routeId)||planning.routes.find(r=>r.name===task.name)||selectedRoute.value;prepareTask(route);repeatSource.value=task.id;taskForm.value.name=`${task.name} · 再次执行`}
function createTask(){if(!taskForm.value.name.trim()||!compatibleDevices.value.some(d=>d.id===taskForm.value.device))return;const r=formRoute.value;emit('create',{id:`T-DEMO-${Date.now()}`,name:taskForm.value.name.trim(),kind:'日常巡检',state:'待执行',progress:0,device:taskForm.value.device,event:null,start:taskForm.value.mode==='定时执行'?taskForm.value.schedule.replace('T',' '):'待下发',schedule:taskForm.value.mode==='定时执行'?taskForm.value.schedule.replace('T',' '):'立即执行',duration:'0 分钟',points:`0 / ${r.points.length}`,note:'任务已创建，等待下发。',routeId:r.id,routeName:r.name,routePoints:copy(r.points),repeatOf:repeatSource.value});taskDialog.value.close();missionFilter.value='全部';setArea('missions');emit('notify','已创建独立任务，航线仍可继续复用')}
function viewTask(task){emit('select',task);setArea('monitor')}
function importSample(){editRoute(null);planning.draft={...copy(initialRoutes[0]),id:`R-${Date.now()}`,name:'北区巡护示例',area:'北区 · 示例导入',uses:0,updated:'刚刚'};drawing.value=false;importDialog.value.close();emit('notify','示例航线已载入，请检查参数后保存')}
onMounted(()=>{sync();window.addEventListener('hashchange',sync)})
onBeforeUnmount(()=>window.removeEventListener('hashchange',sync))
</script>
