import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const read = (path) => readFileSync(new URL(path, import.meta.url), 'utf8')

const deliveryApiSource = read('../src/api/fire/delivery.ts')
const tsaSource = read('../src/pages/page-web/projects/tsa.vue')
const tsaTemplateSource = tsaSource.split('<script')[0]
const waylineSource = read('../src/pages/page-web/projects/wayline.vue')
const waylineTemplateSource = waylineSource.split('<script')[0]
const fireActionButtonsSource = read('../src/components/fire/ActionButtons.vue')
const fireMissionDetailSource = read('../src/pages/page-web/projects/fire/FireMissionDetail.vue')

test('fc100 delivery api exposes mission task and flight command wrappers', () => {
  assert.match(deliveryApiSource, /deviceSn:\s*string/)
  assert.match(deliveryApiSource, /deviceType:\s*string/)
  assert.match(deliveryApiSource, /online:\s*string/)
  assert.match(deliveryApiSource, /bindStatus:\s*string/)
  assert.match(deliveryApiSource, /DeliveryWaylineDTO/)
  assert.match(deliveryApiSource, /DeliveryTaskOperationResult/)
  assert.match(deliveryApiSource, /createTask:\s*\(no:\s*string/)
  assert.match(deliveryApiSource, /startTask:\s*\(no:\s*string/)
  assert.match(deliveryApiSource, /emergencyStop:\s*\(no:\s*string/)
  assert.match(deliveryApiSource, /returnHome:\s*\(no:\s*string/)
  assert.match(deliveryApiSource, /releaseHook:\s*\(no:\s*string/)
  assert.match(deliveryApiSource, /land:\s*\(no:\s*string/)
  assert.match(deliveryApiSource, /commandStatus:\s*\(no:\s*string/)
  assert.match(deliveryApiSource, /importCreateWaylineTask:\s*\(body:\s*FormData/)
  assert.match(deliveryApiSource, /listWaylines:\s*\(page\?:\s*number,\s*pageSize\?:\s*number/)
  assert.match(deliveryApiSource, /createWaylineTask:\s*\(body:/)
  assert.match(deliveryApiSource, /startWaylineTask:\s*\(taskId:\s*string/)
  assert.match(deliveryApiSource, /deviceSn\?:\s*string/)
  assert.match(deliveryApiSource, /waylineTaskStatus:\s*\(taskId:\s*string/)
  assert.match(deliveryApiSource, /sendDeviceCommand:\s*\(deviceSn:\s*string,\s*method:\s*string/)
  assert.match(deliveryApiSource, /prepareFireMissionDeliveryTask:\s*\(no:\s*string,\s*body:/)
  assert.match(deliveryApiSource, /\/api\/fire\/missions\/\$\{no\}\/delivery\/prepare-task/)
  assert.match(deliveryApiSource, /FC100_DELIVERY_DEVICE_COMMANDS/)
  assert.match(deliveryApiSource, /ropeDown:\s*'hoist_control'/)
  assert.match(deliveryApiSource, /ropeUp:\s*'hoist_control'/)
  assert.match(deliveryApiSource, /ropeStop:\s*'hoist_control'/)
  assert.match(deliveryApiSource, /releaseHook:\s*'hoist_hook_control'/)
  assert.match(deliveryApiSource, /sendFc100RopeDownCommand:\s*\(deviceSn:\s*string,\s*body:/)
  assert.match(deliveryApiSource, /sendFc100RopeUpCommand:\s*\(deviceSn:\s*string,\s*body:/)
  assert.match(deliveryApiSource, /sendFc100RopeStopCommand:\s*\(deviceSn:\s*string,\s*body:/)
  assert.match(deliveryApiSource, /sendFc100ReleaseHookCommand:\s*\(deviceSn:\s*string,\s*body:/)
  assert.match(deliveryApiSource, /sendFc100RopeDownCommand:[^\n]*\n\s*deliveryApi\.sendDeviceCommand\(deviceSn,\s*FC100_DELIVERY_DEVICE_COMMANDS\.ropeDown,\s*withFc100CommandData\(body,\s*\{\s*mode:\s*0\s*\}\)\)/)
  assert.match(deliveryApiSource, /sendFc100RopeStopCommand:[^\n]*\n\s*deliveryApi\.sendDeviceCommand\(deviceSn,\s*FC100_DELIVERY_DEVICE_COMMANDS\.ropeStop,\s*withFc100CommandData\(body,\s*\{\s*mode:\s*1\s*\}\)\)/)
  assert.doesNotMatch(deliveryApiSource, /sendFc100RopeStopCommand:[\s\S]*?\{\s*mode:\s*3\s*\}/)
  assert.match(deliveryApiSource, /sendFc100RopeUpCommand:[^\n]*\n\s*deliveryApi\.sendDeviceCommand\(deviceSn,\s*FC100_DELIVERY_DEVICE_COMMANDS\.ropeUp,\s*withFc100CommandData\(body,\s*\{\s*mode:\s*2\s*\}\)\)/)
  assert.match(deliveryApiSource, /\/api\/fire\/missions\/\$\{no\}\/delivery\/emergency-stop/)
  assert.match(deliveryApiSource, /\/api\/fire\/missions\/\$\{no\}\/delivery\/return-home/)
  assert.match(deliveryApiSource, /\/api\/fire\/missions\/\$\{no\}\/delivery\/release-hook/)
  assert.match(deliveryApiSource, /\/api\/fire\/missions\/\$\{no\}\/delivery\/land/)
  assert.match(deliveryApiSource, /\/api\/fire\/missions\/\$\{no\}\/delivery\/commands\/status/)
  assert.match(deliveryApiSource, /\/api\/fire\/delivery\/wayline-tasks\/import-create/)
  assert.match(deliveryApiSource, /\/api\/fire\/delivery\/waylines/)
  assert.match(deliveryApiSource, /\/api\/fire\/delivery\/wayline-tasks\/create-from-wayline/)
  assert.match(deliveryApiSource, /\/api\/fire\/delivery\/wayline-tasks\/\$\{taskId\}\/start/)
  assert.match(deliveryApiSource, /\/api\/fire\/delivery\/wayline-tasks\/\$\{taskId\}\/status/)
  assert.match(deliveryApiSource, /\/api\/fire\/delivery\/devices\/\$\{deviceSn\}\/commands\/\$\{method\}/)
})

test('fire mission action buttons combine route generation and fc100 delivery push without starting task', () => {
  assert.match(fireActionButtonsSource, /PREPARE_FC100_DELIVERY/)
  assert.match(fireActionButtonsSource, /生成航线并推送FC100/)
  assert.match(fireActionButtonsSource, /deliveryApi\.prepareFireMissionDeliveryTask/)
  assert.match(fireActionButtonsSource, /props\.actions\.includes\('APPROVE'\)/)
  assert.match(fireActionButtonsSource, /:disabled="a === 'PREPARE_FC100_DELIVERY' && !canPrepareFc100Delivery"/)
  assert.match(fireActionButtonsSource, /先审批任务，填写FC100、起飞点和风场参数/)
  assert.match(fireActionButtonsSource, /case 'PREPARE_FC100_DELIVERY':\n\s*await doSimple\(\(\) => deliveryApi\.prepareFireMissionDeliveryTask\(no,\s*op\),\s*'生成航线并推送FC100'\)\n\s*break/)
  assert.match(fireActionButtonsSource, /GEN_WP/)
  assert.match(fireActionButtonsSource, /EXP_KMZ/)
  assert.match(fireActionButtonsSource, /CREATE_DELIVERY_TASK/)
})

test('fire mission detail keeps available actions near the top of the page', () => {
  assert.match(fireMissionDetailSource, /class="mission-detail-actions-card"/)
  assert.match(fireMissionDetailSource, /mission-detail-actions-card[\s\S]*position:\s*sticky/)
  assert.match(fireMissionDetailSource, /<a-card title="可用操作" size="small" class="mission-detail-actions-card">[\s\S]*<ActionButtons/)
  assert.match(fireMissionDetailSource, /<a-card title="可用操作" size="small" class="mission-detail-actions-card">[\s\S]*<!-- 区 1: 基本信息 -->/)
  assert.doesNotMatch(fireMissionDetailSource, />\s*执行航线任务\s*</)
  assert.doesNotMatch(fireMissionDetailSource, />\s*重新生成并推送FC100\s*</)
})

test('wayline page exposes fc100 terminal delivery controls in delivery wayline flow', () => {
  assert.match(waylineTemplateSource, /导入FC100任务/)
  assert.match(waylineTemplateSource, /fc100-direct-wayline-upload/)
  assert.match(waylineTemplateSource, /:before-upload="beforeFc100WaylineUpload"/)
  assert.match(waylineTemplateSource, /:custom-request="uploadFc100WaylineFile"/)
  assert.match(waylineSource, /function beforeFc100WaylineUpload/)
  assert.match(waylineSource, /const uploadFc100WaylineFile/)
  assert.match(waylineSource, /deliveryApi\.importCreateWaylineTask/)
  assert.match(waylineSource, /fileData\.append\('deviceSn',\s*deviceSn\)/)
  assert.match(waylineSource, /fileData\.append\('taskName',\s*sanitizeDjiWaylineName/)
  assert.match(waylineTemplateSource, /到点后投放控制/)
  assert.match(waylineTemplateSource, /确认航线到达终点并悬停后再操作/)
  assert.match(waylineTemplateSource, /handleFc100RopeDown/)
  assert.match(waylineTemplateSource, /handleFc100RopeStop/)
  assert.match(waylineTemplateSource, /handleFc100RopeUp/)
  assert.match(waylineTemplateSource, /handleFc100ReleaseHook/)
  assert.match(waylineTemplateSource, /handleFc100ReturnHome/)
  assert.match(waylineTemplateSource, />\s*放绳\s*</)
  assert.match(waylineTemplateSource, />\s*停止\s*</)
  assert.match(waylineTemplateSource, />\s*收绳\s*</)
  assert.match(waylineTemplateSource, />\s*脱钩\s*</)
  assert.match(waylineTemplateSource, />\s*返航\s*</)
  assert.match(waylineSource, /function canUseFc100TerminalControls/)
  assert.match(waylineSource, /function confirmFc100TerminalAction/)
  assert.match(waylineSource, /deliveryApi\.sendFc100RopeDownCommand/)
  assert.match(waylineSource, /deliveryApi\.sendFc100RopeStopCommand/)
  assert.match(waylineSource, /deliveryApi\.sendFc100RopeUpCommand/)
  assert.match(waylineSource, /deliveryApi\.sendFc100ReleaseHookCommand/)
  assert.match(waylineSource, /deliveryApi\.sendDeviceCommand\(deviceSn,\s*'return_home'/)
  assert.match(waylineSource, /let fc100RealtimeTimer:\s*number\s*\|\s*null\s*=\s*null/)
  assert.match(waylineSource, /function startFc100RealtimeRefresh/)
  assert.match(waylineSource, /window\.setInterval\(refreshFc100RealtimeState,\s*3000\)/)
  assert.match(waylineSource, /function stopFc100RealtimeRefresh/)
  assert.match(waylineSource, /refreshFc100SelectedDeviceProps\(\)/)
  assert.match(waylineSource, /refreshFc100TaskStatus\(false\)/)
  assert.match(waylineSource, /startFc100RealtimeRefresh\(\)/)
  assert.match(waylineSource, /stopFc100RealtimeRefresh\(\)/)
  assert.match(waylineSource, /fc100-terminal-actions/)
  assert.match(waylineSource, /fc100-terminal-actions__primary/)
  assert.match(waylineSource, /fc100-terminal-actions__danger/)
})

test('tsa page renders fc100 delivery verification controls', () => {
  assert.match(tsaSource, /deliveryApi/)
  assert.match(tsaTemplateSource, /fc100DeliveryFormState/)
  assert.match(tsaTemplateSource, /FC100 云端设备/)
  assert.match(tsaTemplateSource, /header="监测设备"/)
  assert.match(tsaTemplateSource, /header="投放设备"/)
  assert.doesNotMatch(tsaTemplateSource, /header="在线设备"/)
  assert.match(tsaTemplateSource, /刷新设备/)
  assert.match(tsaTemplateSource, /fc100DeliveryFormState\.devices/)
  assert.match(tsaTemplateSource, /handleFc100RefreshDevices/)
  assert.match(tsaTemplateSource, /handleFc100SelectDevice/)
  assert.match(tsaTemplateSource, /@click="handleFc100SelectDevice\(selectedFc100DeliveryDevice\.deviceSn\)"/)
  assert.doesNotMatch(tsaTemplateSource, />\s*物模型\s*</)
  assert.match(tsaTemplateSource, /<div class="fc100-device-sn">\{\{ formatFc100DeviceModel\(selectedFc100DeliveryDevice\) \}\}<\/div>/)
  assert.match(tsaTemplateSource, /\{\{ selectedFc100DeliveryDevice\.deviceSn \}\} · \{\{ selectedFc100DeliveryDevice\.bindStatus \|\| '--' \}\}/)
  assert.match(tsaSource, /fc100-link-status--online/)
  assert.match(tsaTemplateSource, /formatFc100ConnectionLabel\(fc100DeliveryFormState\.selectedDeviceProps\.onlineStatus\)/)
  assert.match(tsaSource, /function formatFc100DeviceModel/)
  assert.match(tsaSource, /DJI FlyCart 100/)
  assert.match(tsaSource, /function getFc100ConnectionStatusClass/)
  assert.match(tsaSource, /function formatFc100ConnectionLabel/)
  assert.match(tsaTemplateSource, /FC100 火情任务/)
  assert.doesNotMatch(tsaTemplateSource, /FC100 航线导入执行/)
  assert.doesNotMatch(tsaTemplateSource, /FC100 已有航线/)
  assert.doesNotMatch(tsaTemplateSource, /刷新航线/)
  assert.doesNotMatch(tsaTemplateSource, /用此航线创建任务/)
  assert.doesNotMatch(tsaTemplateSource, /选择 KMZ\/KML/)
  assert.doesNotMatch(tsaTemplateSource, /导入并创建任务/)
  assert.doesNotMatch(tsaTemplateSource, /开始执行航线/)
  assert.match(tsaTemplateSource, /任务编号/)
  assert.match(tsaTemplateSource, /创建任务/)
  assert.match(tsaTemplateSource, /开始航线/)
  assert.match(tsaTemplateSource, /任务状态/)
  assert.match(tsaTemplateSource, /FC100 急停/)
  assert.match(tsaTemplateSource, /FC100 返航/)
  assert.match(tsaTemplateSource, /开钩投放/)
  assert.match(tsaTemplateSource, /FC100 降落/)
  assert.match(tsaTemplateSource, /命令状态/)
})

test('tsa fc100 device card uses an inline aircraft-only dropdown menu', () => {
  assert.doesNotMatch(tsaTemplateSource, /<a-select[\s\S]*fc100DeliveryFormState\.selectedDeviceSn/)
  assert.match(tsaTemplateSource, /class="fc100-device-card-dropdown delivery-device-card-dropdown"/)
  assert.match(tsaTemplateSource, /v-if="selectableFc100DeliveryDevices\.length > 0"/)
  assert.match(tsaTemplateSource, /<a-dropdown[\s\S]*class="fc100-device-card-dropdown delivery-device-card-dropdown"/)
  assert.match(tsaTemplateSource, /v-for="device in selectableFc100DeliveryDevices"/)
  assert.match(tsaSource, /function isFc100AircraftDevice[\s\S]*bindStatus[\s\S]*!== 'rc'/)
  assert.match(tsaSource, /const selectableFc100DeliveryDevices\s*=\s*computed/)
  assert.match(tsaSource, /fc100DeliveryFormState\.devices\.filter\(isFc100AircraftDevice\)/)
})

test('tsa monitoring device card reuses the fc100 card dropdown and telemetry grid', () => {
  assert.doesNotMatch(tsaTemplateSource, /<a-select[\s\S]*selectedMonitoringDeviceSn/)
  assert.doesNotMatch(tsaTemplateSource, /placeholder="选择监测飞行器"/)
  assert.match(tsaTemplateSource, /class="fc100-device-card-dropdown monitoring-device-card-dropdown"/)
  assert.match(tsaTemplateSource, /v-if="selectableMonitoringDevices\.length > 0"/)
  assert.match(tsaTemplateSource, /v-for="option in selectableMonitoringDevices"/)
  assert.match(tsaSource, /function isMonitoringAircraftDevice[\s\S]*rc plus/)
  assert.match(tsaSource, /function normalizeMonitoringModelName[\s\S]*Matrice 4T/)
  assert.match(tsaSource, /function formatMonitoringDeviceModel[\s\S]*normalizeMonitoringModelName\(device\.model\) \|\| device\.callsign \|\| device\.sn/)
  assert.doesNotMatch(tsaSource, /MSDK Aircraft/)
  assert.doesNotMatch(tsaSource, /\$\{device\.model\} - \$\{device\.callsign\}/)
  assert.match(tsaSource, /const selectableMonitoringDevices\s*=\s*computed/)
  assert.match(tsaSource, /selectedMonitoringDeviceSn\.value = pickSelectedDeviceSn\(selectableMonitoringDevices\.value/)
  for (const label of ['连接状态', '电量', 'RTK', '飞行模式', '飞行中', '经度', '纬度', '高度', '水平速度', '垂直速度', '返航距离', '风速', '更新时间']) {
    assert.match(tsaTemplateSource, new RegExp(`<span>${label}</span>`))
  }
})

test('tsa page calls fc100 delivery endpoints from visible handlers', () => {
  assert.match(tsaSource, /async function handleFc100CreateTask/)
  assert.match(tsaSource, /async function handleFc100StartTask/)
  assert.match(tsaSource, /async function handleFc100TaskStatus/)
  assert.match(tsaSource, /async function handleFc100EmergencyStop/)
  assert.match(tsaSource, /async function handleFc100ReturnHome/)
  assert.match(tsaSource, /async function handleFc100ReleaseHook/)
  assert.match(tsaSource, /async function handleFc100Land/)
  assert.match(tsaSource, /async function handleFc100CommandStatus/)
  assert.match(tsaSource, /deliveryApi\.createTask/)
  assert.match(tsaSource, /deliveryApi\.startTask/)
  assert.match(tsaSource, /deliveryApi\.status/)
  assert.match(tsaSource, /deliveryApi\.listDevices/)
  assert.match(tsaSource, /deliveryApi\.deviceProps/)
  assert.match(tsaSource, /deliveryApi\.emergencyStop/)
  assert.match(tsaSource, /deliveryApi\.returnHome/)
  assert.match(tsaSource, /deliveryApi\.releaseHook/)
  assert.match(tsaSource, /deliveryApi\.land/)
  assert.match(tsaSource, /deliveryApi\.commandStatus/)
  assert.match(tsaSource, /getFc100OperationDisplayText/)
  assert.match(tsaSource, /displayMessage/)
  assert.doesNotMatch(tsaSource, /body\\?\\.code === 0/)
  assert.doesNotMatch(tsaSource, /body\\?\\.code !== 0/)
})
