import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const read = (path) => readFileSync(new URL(path, import.meta.url), 'utf8')

const deliveryApiSource = read('../src/api/fire/delivery.ts')
const tsaSource = read('../src/pages/page-web/projects/tsa.vue')

test('fc100 delivery api exposes mission task and flight command wrappers', () => {
  assert.match(deliveryApiSource, /deviceSn:\s*string/)
  assert.match(deliveryApiSource, /deviceType:\s*string/)
  assert.match(deliveryApiSource, /online:\s*string/)
  assert.match(deliveryApiSource, /bindStatus:\s*string/)
  assert.match(deliveryApiSource, /DeliveryWaylineDTO/)
  assert.match(deliveryApiSource, /DeliveryTaskOperationResult/)
  assert.match(deliveryApiSource, /createTask:\s*\(no:\s*string/)
  assert.match(deliveryApiSource, /startTask:\s*\(no:\s*string/)
  assert.match(deliveryApiSource, /emergencyStop:\s*\(no:\s*string/)
  assert.match(deliveryApiSource, /returnHome:\s*\(no:\s*string/)
  assert.match(deliveryApiSource, /land:\s*\(no:\s*string/)
  assert.match(deliveryApiSource, /commandStatus:\s*\(no:\s*string/)
  assert.match(deliveryApiSource, /importCreateWaylineTask:\s*\(body:\s*FormData/)
  assert.match(deliveryApiSource, /listWaylines:\s*\(page\?:\s*number,\s*pageSize\?:\s*number/)
  assert.match(deliveryApiSource, /createWaylineTask:\s*\(body:/)
  assert.match(deliveryApiSource, /startWaylineTask:\s*\(taskId:\s*string/)
  assert.match(deliveryApiSource, /deviceSn\?:\s*string/)
  assert.match(deliveryApiSource, /waylineTaskStatus:\s*\(taskId:\s*string/)
  assert.match(deliveryApiSource, /sendDeviceCommand:\s*\(deviceSn:\s*string,\s*method:\s*string/)
  assert.match(deliveryApiSource, /\/api\/fire\/missions\/\$\{no\}\/delivery\/emergency-stop/)
  assert.match(deliveryApiSource, /\/api\/fire\/missions\/\$\{no\}\/delivery\/return-home/)
  assert.match(deliveryApiSource, /\/api\/fire\/missions\/\$\{no\}\/delivery\/land/)
  assert.match(deliveryApiSource, /\/api\/fire\/missions\/\$\{no\}\/delivery\/commands\/status/)
  assert.match(deliveryApiSource, /\/api\/fire\/delivery\/wayline-tasks\/import-create/)
  assert.match(deliveryApiSource, /\/api\/fire\/delivery\/waylines/)
  assert.match(deliveryApiSource, /\/api\/fire\/delivery\/wayline-tasks\/create-from-wayline/)
  assert.match(deliveryApiSource, /\/api\/fire\/delivery\/wayline-tasks\/\$\{taskId\}\/start/)
  assert.match(deliveryApiSource, /\/api\/fire\/delivery\/wayline-tasks\/\$\{taskId\}\/status/)
  assert.match(deliveryApiSource, /\/api\/fire\/delivery\/devices\/\$\{deviceSn\}\/commands\/\$\{method\}/)
})

test('tsa page renders fc100 delivery verification controls', () => {
  assert.match(tsaSource, /deliveryApi/)
  assert.match(tsaSource, /fc100DeliveryFormState/)
  assert.match(tsaSource, /FC100 云端设备/)
  assert.match(tsaSource, /刷新设备/)
  assert.match(tsaSource, /fc100DeliveryFormState\.devices/)
  assert.match(tsaSource, /handleFc100RefreshDevices/)
  assert.match(tsaSource, /handleFc100SelectDevice/)
  assert.match(tsaSource, /FC100 火情任务/)
  assert.match(tsaSource, /FC100 航线导入执行/)
  assert.match(tsaSource, /FC100 已有航线/)
  assert.match(tsaSource, /刷新航线/)
  assert.match(tsaSource, /用此航线创建任务/)
  assert.match(tsaSource, /选择 KMZ\/KML/)
  assert.match(tsaSource, /导入并创建任务/)
  assert.match(tsaSource, /开始执行航线/)
  assert.match(tsaSource, /执行前检查/)
  assert.match(tsaSource, /任务编号/)
  assert.match(tsaSource, /创建任务/)
  assert.match(tsaSource, /开始航线/)
  assert.match(tsaSource, /任务状态/)
  assert.match(tsaSource, /FC100 急停/)
  assert.match(tsaSource, /FC100 返航/)
  assert.match(tsaSource, /FC100 降落/)
  assert.match(tsaSource, /命令状态/)
})

test('tsa page calls fc100 delivery endpoints from visible handlers', () => {
  assert.match(tsaSource, /async function handleFc100CreateTask/)
  assert.match(tsaSource, /async function handleFc100StartTask/)
  assert.match(tsaSource, /async function handleFc100TaskStatus/)
  assert.match(tsaSource, /async function handleFc100EmergencyStop/)
  assert.match(tsaSource, /async function handleFc100ReturnHome/)
  assert.match(tsaSource, /async function handleFc100Land/)
  assert.match(tsaSource, /async function handleFc100CommandStatus/)
  assert.match(tsaSource, /function handleFc100DirectWaylineFile/)
  assert.match(tsaSource, /async function handleFc100ImportCreateWaylineTask/)
  assert.match(tsaSource, /async function handleFc100RefreshWaylines/)
  assert.match(tsaSource, /async function handleFc100CreateTaskFromWayline/)
  assert.match(tsaSource, /async function handleFc100StartDirectWaylineTask/)
  assert.match(tsaSource, /async function refreshFc100DirectDeviceProps/)
  assert.match(tsaSource, /function buildFc100StartPreflightWarnings/)
  assert.match(tsaSource, /async function handleFc100DirectWaylineTaskStatus/)
  assert.match(tsaSource, /deliveryApi\.createTask/)
  assert.match(tsaSource, /deliveryApi\.startTask/)
  assert.match(tsaSource, /deliveryApi\.status/)
  assert.match(tsaSource, /deliveryApi\.listDevices/)
  assert.match(tsaSource, /deliveryApi\.deviceProps/)
  assert.match(tsaSource, /deliveryApi\.emergencyStop/)
  assert.match(tsaSource, /deliveryApi\.returnHome/)
  assert.match(tsaSource, /deliveryApi\.land/)
  assert.match(tsaSource, /deliveryApi\.commandStatus/)
  assert.match(tsaSource, /deliveryApi\.importCreateWaylineTask/)
  assert.match(tsaSource, /deliveryApi\.listWaylines/)
  assert.match(tsaSource, /deliveryApi\.createWaylineTask/)
  assert.match(tsaSource, /deliveryApi\.startWaylineTask\(taskId,\s*deviceSn\)/)
  assert.match(tsaSource, /deliveryApi\.waylineTaskStatus/)
  assert.match(tsaSource, /deliveryApi\.sendDeviceCommand/)
  assert.match(tsaSource, /getFc100OperationDisplayText/)
  assert.match(tsaSource, /displayMessage/)
  assert.doesNotMatch(tsaSource, /body\\?\\.code === 0/)
  assert.doesNotMatch(tsaSource, /body\\?\\.code !== 0/)
})
