import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const fireEventListPath = new URL('../src/pages/page-web/projects/fire/FireEventList.vue', import.meta.url)
const fireMissionListPath = new URL('../src/pages/page-web/projects/fire/FireMissionList.vue', import.meta.url)
const fireActionButtonsPath = new URL('../src/components/fire/ActionButtons.vue', import.meta.url)
const source = readFileSync(fireEventListPath, 'utf8')
const missionListSource = readFileSync(fireMissionListPath, 'utf8')
const actionButtonsSource = readFileSync(fireActionButtonsPath, 'utf8')

test('fire event list renders visible and thermal recognition images separately', () => {
  assert.match(source, /record\.visibleImageUrl/)
  assert.match(source, /record\.thermalImageUrl/)
  assert.match(source, /可见光/)
  assert.match(source, /红外/)
  assert.match(source, /openPreview\(record\.visibleImageUrl\)/)
  assert.match(source, /openPreview\(record\.thermalImageUrl\)/)
  assert.doesNotMatch(source, /:src="record\.thermalImageUrl \|\| record\.visibleImageUrl"/)
  assert.doesNotMatch(source, /openPreview\(record\.thermalImageUrl \|\| record\.visibleImageUrl\)/)
})

test('fire event list formats thermal temperature to one decimal place', () => {
  assert.match(source, /formatThermalTemperature/)
  assert.match(source, /formatThermalTemperature\(record\.thermalTemperature\)/)
  assert.match(source, /Number\(value\)/)
  assert.match(source, /\.toFixed\(1\)/)
})

test('fire event list relies on annotated infrared images for temperature placement', () => {
  assert.match(source, /thermal-image-wrap/)
  assert.doesNotMatch(source, /thermal-temp-badge/)
  assert.doesNotMatch(source, /preview-temp-badge/)
  assert.doesNotMatch(source, /previewThermalTemperature/)
  assert.doesNotMatch(source, /openPreview\(record\.thermalImageUrl, record\.thermalTemperature\)/)
  assert.doesNotMatch(source, /openPreview\(record\.thermalImageUrl!, record\.thermalTemperature\)/)
})

test('fire event preview preserves cache-busting query while switching raw and annotated images', () => {
  assert.match(source, /function recognitionImageUrlForMode/)
  assert.match(source, /const hashIndex = url\.indexOf\('#'\)/)
  assert.match(source, /const queryIndex = withoutHash\.indexOf\('\?'\)/)
  assert.ok(source.includes("path.replace(/-raw\\.jpg$/, '-annotated.jpg')"))
  assert.ok(source.includes("annotatedPath.replace(/-annotated\\.jpg$/, '-raw.jpg')"))
  assert.ok(source.includes('return nextPath + query + hash'))
})

test('fire event list wraps long device serial numbers inside their column', () => {
  assert.match(source, /#deviceSnCell/)
  assert.match(source, /class="table-text-wrap"/)
  assert.match(source, /word-break: break-all/)
  assert.match(source, /overflow-wrap: anywhere/)
  assert.match(source, /slots: \{ customRender: 'deviceSnCell' \}/)
})

test('fire event list localizes event status and explains partial history snapshots', () => {
  assert.match(source, /displayFireLevel/)
  assert.match(source, /HIGH: '高'/)
  assert.match(source, /MEDIUM: '中'/)
  assert.match(source, /LOW: '低'/)
  assert.match(source, /displayEventStatus/)
  assert.match(source, /LOW_CONFIDENCE: '低置信度'/)
  assert.match(source, /MISSION_CREATED: '已创建任务'/)
  assert.match(source, /displayHistoryAction/)
  assert.match(source, /CREATED: '首次热源确认'/)
  assert.match(source, /MERGED: '热源复检'/)
  assert.match(source, /VISIBLE_CONFIRM: '可见光确认'/)
  assert.match(source, /VISIBLE_PENDING: '可见光确认中'/)
  assert.match(source, /VISIBLE_REJECTED: '可见光未确认'/)
  assert.match(source, /VISIBLE_CAPTURE_FAILED: '可见光抓图失败'/)
  assert.match(source, /VISIBLE_CONFIRM_FAILED: '可见光确认失败'/)
  assert.match(source, /thermalHistoryCount/)
  assert.ok(source.includes('热源识别 ${total} 次 / 历史记录 ${historyEvents.value.length} 条'))
  assert.match(source, /暂无历史记录/)
})

test('fire event history displays persisted thermal ROI for measurement debugging', () => {
  assert.match(source, /displayThermalRoi/)
  assert.match(source, /record\.thermalRoi/)
  assert.match(source, /测温ROI/)
})

test('fire event history shows visible confirmations as explicit evidence on thermal rows', () => {
  assert.match(source, /historyDisplayRows/)
  assert.match(source, /groupHistoryEvents/)
  assert.match(source, /visibleConfirmation/)
  assert.match(source, /可见光确认图/)
  assert.match(source, /红外证据图/)
  assert.match(source, /visibleStatusText/)
  assert.doesNotMatch(source, /default-expand-all-rows/)
  assert.match(source, /rowKey/)
  assert.match(source, /!isVisibleHistoryAction\(item\.action\)/)
})

test('fire mission operations live in mission list instead of fire event list', () => {
  assert.doesNotMatch(source, /missionApi/)
  assert.doesNotMatch(source, /deliveryApi/)
  assert.doesNotMatch(source, /openApproveDeliveryModal/)
  assert.doesNotMatch(source, /submitApproveDelivery/)
  assert.doesNotMatch(source, /审批并生成航线/)
  assert.doesNotMatch(source, /生成航线任务/)
  assert.doesNotMatch(source, /fire-mission-detail/)
  assert.doesNotMatch(source, /router\.push/)

  assert.match(missionListSource, /import ActionButtons/)
  assert.match(missionListSource, /<ActionButtons/)
  assert.match(missionListSource, /:mission-no="record\.missionNo"/)
  assert.match(missionListSource, /:actions="record\.availableActions"/)
  assert.match(missionListSource, /@refresh="loadMissions\(statusFilter \|\| undefined\)"/)
  assert.match(missionListSource, /fire-mission-detail/)
  assert.match(missionListSource, /:scroll="\{ x: 1280 \}"/)
  assert.doesNotMatch(missionListSource, /fixed:\s*'right'/)
  assert.match(missionListSource, /暂无可执行操作/)
  assert.match(missionListSource, /const approvedMissionStatuses = new Set<FireMissionStatus>/)
  assert.match(missionListSource, /missions\.value = \(res\.data\.data \?\? \[\]\)\.filter\(mission =>\s*approvedMissionStatuses\.has\(mission\.status\)\)/)
  assert.match(missionListSource, /import \{ eventApi \}/)
  assert.match(missionListSource, /const fireEventsById = ref<Record<number, FireEventDTO>>/)
  assert.match(missionListSource, /eventApi\.list\(\{ size: 500 \}\)/)
  assert.match(missionListSource, /title: '火情信息'/)
  assert.match(missionListSource, /title: '无人机信息'/)
  assert.doesNotMatch(missionListSource, /title: '飞机SN'/)
  assert.match(missionListSource, /#aircraftCell/)
  assert.match(missionListSource, /slots: \{ customRender: 'aircraftCell' \}/)
  assert.match(missionListSource, /function formatAircraftModel/)
  assert.match(missionListSource, /DJI FlyCart 100/)
  assert.match(missionListSource, /title: '运行状态'/)
  assert.match(missionListSource, /#fireEventCell/)
  assert.match(missionListSource, /#statusCell/)
  assert.match(missionListSource, /#actionCell/)
  assert.match(missionListSource, /slots: \{ customRender: 'fireEventCell' \}/)
  assert.match(missionListSource, /slots: \{ customRender: 'statusCell' \}/)
  assert.match(missionListSource, /slots: \{ customRender: 'actionCell' \}/)
  assert.doesNotMatch(missionListSource, /#bodyCell/)
  assert.match(missionListSource, /function getMissionFireEvent/)
  assert.match(missionListSource, /function getMissionRuntimeText/)
  assert.doesNotMatch(missionListSource, /value: 'CREATED'/)
  assert.doesNotMatch(missionListSource, /value: 'WAITING_REVIEW'/)
  assert.doesNotMatch(missionListSource, /value: 'REJECTED'/)
  assert.doesNotMatch(missionListSource, /value: 'CANCELLED'/)
  assert.doesNotMatch(source, /\/missions\//)
})

test('fire mission list uses a calmer grouped operations layout', () => {
  assert.match(missionListSource, /class="fire-mission-page"/)
  assert.match(missionListSource, /class="fire-mission-toolbar"/)
  assert.match(missionListSource, /class="mission-number-cell"/)
  assert.match(missionListSource, /class="mission-fire-summary"/)
  assert.match(missionListSource, /class="mission-meta-row"/)
  assert.match(missionListSource, /class="mission-action-panel"/)
  assert.match(missionListSource, /class="mission-action-primary"/)
  assert.match(missionListSource, /class="mission-action-secondary"/)
  assert.match(missionListSource, /class="mission-detail-button"/)
  assert.match(missionListSource, /:scroll="\{ x: 1280 \}"/)
  assert.doesNotMatch(missionListSource, /fixed:\s*'right'/)
  assert.match(missionListSource, /\.fire-mission-table/)
  assert.match(missionListSource, /\.mission-action-primary[\s\S]*flex-wrap:\s*wrap/)
  assert.match(missionListSource, /\.mission-action-secondary[\s\S]*flex-wrap:\s*wrap/)
})

test('fire mission list places primary actions and fire badge where operators scan first', () => {
  assert.match(missionListSource, /<ActionButtons[\s\S]*:only-actions="\['PREPARE_FC100_DELIVERY'\]"[\s\S]*\/>[\s\S]*<a-button class="mission-detail-button"/)
  assert.match(missionListSource, /<ActionButtons[\s\S]*:exclude-actions="\['PREPARE_FC100_DELIVERY'\]"[\s\S]*\/>/)
  assert.match(missionListSource, /<span class="fire-level-pill"[\s\S]*<\/span>\s*<strong>\{\{ getMissionFireEvent\(record\)\?\.eventId/)
  assert.match(missionListSource, /\.mission-title-line[\s\S]*display:\s*flex/)
  assert.match(missionListSource, /\.mission-title-line[\s\S]*align-items:\s*center/)
  assert.match(missionListSource, /\.mission-title-line[\s\S]*strong[\s\S]*display:\s*inline/)
  assert.match(missionListSource, /\.fire-level-pill[\s\S]*display:\s*inline-flex/)
  assert.match(missionListSource, /\.fire-level-pill[\s\S]*justify-content:\s*center/)
  assert.match(missionListSource, /\.mission-action-secondary[\s\S]*\.fire-action-button--force-fail[\s\S]*order:\s*20/)
  assert.match(missionListSource, /\.mission-action-secondary[\s\S]*\.fire-action-button--cancel[\s\S]*order:\s*30/)
  assert.match(missionListSource, /\.mission-action-primary\s+:deep\(\.ant-btn\)[\s\S]*height:\s*34px/)
  assert.match(missionListSource, /\.mission-action-secondary\s+:deep\(\.ant-btn\)[\s\S]*height:\s*34px/)
  assert.match(missionListSource, /\.mission-detail-button[\s\S]*display:\s*inline-flex/)
  assert.match(missionListSource, /\.mission-detail-button[\s\S]*align-items:\s*center/)
  assert.match(missionListSource, /\.mission-detail-button[\s\S]*justify-content:\s*center/)
  assert.doesNotMatch(missionListSource, />\s*任务 ID\s*</)

  assert.match(actionButtonsSource, /onlyActions\?:\s*string\[\]/)
  assert.match(actionButtonsSource, /excludeActions\?:\s*string\[\]/)
  assert.match(actionButtonsSource, /fire-action-button--\$\{actionClassName\(a\)\}/)
  assert.match(actionButtonsSource, /function actionClassName/)
  assert.match(actionButtonsSource, /function actionSortOrder/)
  assert.match(actionButtonsSource, /FORCE_FAIL:\s*30/)
  assert.match(actionButtonsSource, /CANCEL:\s*40/)
  assert.match(actionButtonsSource, /\.sort\(\(a, b\) => actionSortOrder\(a\) - actionSortOrder\(b\)\)/)
})
