USE `cloud_sample`;

CREATE TABLE IF NOT EXISTS `planned_wayline` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `planned_wayline_id` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT 'uuid',
  `workspace_id` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT 'Which workspace the current planned wayline belongs to.',
  `name` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT 'planned wayline name',
  `aircraft_model_key` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT 'device product enum. format: domain-device_type-sub_type',
  `gateway_sn` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT 'The gateway sn used for this planned wayline.',
  `aircraft_sn` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT 'The aircraft sn used for this planned wayline.',
  `default_height` double NOT NULL COMMENT 'default flight height',
  `max_speed` double NOT NULL COMMENT 'maximum flight speed',
  `waypoints_json` mediumtext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT 'Serialized waypoint list.',
  `status` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT 'draft' COMMENT 'draft/published/archived',
  `published_wayline_id` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'Linked wayline file id after publish.',
  `kmz_url` varchar(1024) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'Generated KMZ file download URL.',
  `kmz_md5` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'Generated KMZ file MD5 fingerprint.',
  `kmz_object_key` varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'Generated KMZ object key.',
  `file_generated_time` bigint DEFAULT NULL COMMENT 'The time when KMZ file was generated.',
  `flight_id` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'DJI flight task id.',
  `dock_sn` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'Target dock sn.',
  `drone_sn` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'Target drone sn.',
  `task_status` varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'Planned wayline task status.',
  `task_status_reason` varchar(512) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'Task status reason or failure message.',
  `task_progress` int DEFAULT NULL COMMENT 'Task execution progress.',
  `prepared_time` bigint DEFAULT NULL COMMENT 'The time when task was prepared.',
  `executed_time` bigint DEFAULT NULL COMMENT 'The time when task started execution.',
  `creator` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '' COMMENT 'The name of the creator.',
  `publisher` varchar(64) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL COMMENT 'The name of the publisher.',
  `publish_time` bigint DEFAULT NULL COMMENT 'The time when this planned wayline was published.',
  `create_time` bigint NOT NULL,
  `update_time` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `planned_wayline_id_UNIQUE` (`planned_wayline_id`),
  KEY `idx_planned_wayline_workspace_id_id` (`workspace_id`,`id`),
  KEY `idx_planned_wayline_workspace_id_planned_wayline_id` (`workspace_id`,`planned_wayline_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COMMENT='Planned wayline draft information.';
