package com.yinxin.uavfir.api

import com.yinxin.uavfir.sdk.PayloadCapability

data class MsdkDeviceStateRequest(
    val gatewaySn: String,
    val aircraftSn: String,
    val online: Boolean,
    val connectionState: String,
    val deviceName: String? = null,
    val model: String? = null,
    val mode: String? = null,
    val latitude: Double? = null,
    val longitude: Double? = null,
    val height: Double? = null,
    val elevation: Double? = null,
    val homeDistance: Double? = null,
    val horizontalSpeed: Double? = null,
    val verticalSpeed: Double? = null,
    val windSpeed: Double? = null,
    val batteryPercent: Int? = null,
    val gpsCount: Int? = null,
    val rtkCount: Int? = null,
    val positionFixed: Boolean? = null,
    val updatedAt: Long = System.currentTimeMillis(),
    val agentVersionName: String? = null,
    val agentVersionCode: Long? = null,
    val waylineCommandSupported: Boolean? = null,
    val capabilities: Map<String, Boolean> = emptyMap(),
    val aircraftModelKey: String? = null,
    val controllerModelKey: String? = null,
    val payloads: List<PayloadCapability> = emptyList(),
    val selectedPayloadPositionIndex: Int? = null,
    val laserSupported: Boolean = false,
    val fireClosedLoopReady: Boolean = false,
    val blockingReasons: List<String> = emptyList(),
)
