<template><section class="cc-page"><div class="cc-heading"><div><span class="cc-eyebrow">UAVFIRE / 巡护指挥台</span><h1>运行总览</h1><p>先关注待复核事件、执行中的任务与设备异常。</p></div><button class="cc-button" :disabled="loading" @click="refresh"><ReloadOutlined />{{ loading?'更新中':'刷新视图' }}</button></div><div v-for="error in errors" :key="error" class="cc-error" role="alert">{{ error }}</div><div class="cc-summary-grid"><router-link class="cc-panel" to="/fire-events"><span>近期待复核事件</span><strong>{{ valid.events?pending.length:'—' }}</strong></router-link><router-link class="cc-panel" to="/task-history"><span>巡检计划执行中</span><strong>{{ valid.tasks?running.length:'—' }}</strong></router-link><router-link class="cc-panel" to="/devices"><span>在线巡护飞机</span><strong>{{ valid.devices?online.length:'—' }}</strong></router-link></div><div class="cc-quicklinks"><router-link class="cc-panel" to="/wayline?view=planner"><EnvironmentOutlined /><span>航线规划<small>航点、巡逻与面状规划</small></span></router-link><router-link class="cc-panel" to="/wayline"><ScheduleOutlined /><span>航线库<small>编辑、导入与再次执行</small></span></router-link><router-link class="cc-panel" to="/fire-missions"><SendOutlined /><span>灭火与投送<small>审批、任务和反馈</small></span></router-link><router-link class="cc-panel" to="/media"><PictureOutlined /><span>媒体资料<small>现场证据与任务成果</small></span></router-link></div><div class="cc-overview-main"><div class="cc-panel cc-overview-map"><CockpitSituationMap :layers="layers" @select="focusEvent" /></div><aside class="cc-panel cc-overview-list"><h2>需要关注</h2><router-link v-for="event in pending.slice(0,5)" :key="event.id" :to="{path:'/fire-events',query:{event:event.eventId}}"><span class="cc-status warn">待复核</span><p>{{ event.eventId }}</p><small>{{ event.deviceSn||'设备未记录' }}</small></router-link><router-link v-for="device in warnings.slice(0,3)" :key="device.aircraftSn" to="/devices"><span class="cc-status warn">低电量</span><p>{{ device.deviceName||device.aircraftSn }} · {{ device.batteryPercent }}%</p></router-link><div v-if="!pending.length&&!warnings.length" class="cc-empty">{{ loading?'正在读取待办…':errors.length?'部分数据暂时不可用':'当前没有待复核事件或低电量提醒' }}</div></aside></div><p class="cc-muted" style="margin-top:16px">{{ updated?'最近更新：'+updated:'等待首次更新' }} · 事件按最近 200 条、巡检计划按最近 100 条记录统计；航线执行见任务中心</p></section></template>
<script setup lang="ts">
import { ref, reactive, computed, onMounted, onBeforeUnmount } from 'vue'
import { useRouter } from 'vue-router'
import { ReloadOutlined, EnvironmentOutlined, ScheduleOutlined, SendOutlined, PictureOutlined } from '@ant-design/icons-vue'
import { eventApi } from '/@/api/fire/event'
import { listMsdkDevices } from '/@/api/msdk-device'
import { getWaylineJobs } from '/@/api/wayline'
import { ELocalStorageKey } from '/@/types'
import CockpitSituationMap from '/@/pages/page-web/projects/CockpitSituationMap.vue'
import { isConnectedMsdkDevice } from '/@/pages/page-web/projects/leadership-cockpit-summary.mjs'
import { buildSituationLayers } from '/@/pages/page-web/projects/leadership-cockpit-situation.mjs'
import { isValidationEvent, eventState, responseData } from '/@/components/command-center/event-model.mjs'
const router = useRouter(); const events = ref<any[]>([]); const devices = ref<any[]>([]); const tasks = ref<any[]>([]); const errors = ref<string[]>([]); const loading = ref(false); const updated = ref('')
const valid = reactive({ events: false, devices: false, tasks: false })
const pending = computed(() => events.value.filter(e => eventState(e).key === 'pending')); const online = computed(() => devices.value.filter(isConnectedMsdkDevice)); const warnings = computed(() => online.value.filter(d => typeof d.batteryPercent === 'number' && d.batteryPercent < 30)); const running = computed(() => tasks.value.filter(t => t.status === 2))
const layers = computed(() => buildSituationLayers({ fireEvents: events.value, msdkDevices: devices.value }))
let timer:ReturnType<typeof setInterval>; let disposed = false
function checked (r:any) { if (r?.code !== 0) throw new Error(r?.message || '读取失败'); return r.data }
async function refresh () { if (loading.value || disposed) return; loading.value = true; const wid = localStorage.getItem(ELocalStorageKey.WorkspaceId) || ''; const results = await Promise.allSettled([eventApi.list({ workspaceId: wid, limit: 200 }, true).then(responseData), listMsdkDevices(true).then(checked), getWaylineJobs(wid, { page: 1, page_size: 100, total: 0 }, true).then(checked)]); if (disposed) return; errors.value = []; results.forEach((r, i) => { const key = ['events', 'devices', 'tasks'][i]; if (r.status === 'fulfilled') { valid[key] = true; if (i === 0)events.value = Array.isArray(r.value) ? r.value.filter(event => !isValidationEvent(event)) : []; if (i === 1)devices.value = r.value || []; if (i === 2)tasks.value = r.value?.list || [] } else { valid[key] = false; errors.value.push(['火情事件', '设备状态', '巡检任务'][i] + '更新失败，已显示数据可能过期。') } }); updated.value = new Date().toLocaleTimeString('zh-CN'); loading.value = false }
function focusEvent (marker:any) { if (typeof marker === 'string' && marker.startsWith('fire:')) router.push({ path: '/fire-events', query: { event: marker.slice(5) } }) }
onMounted(() => { refresh(); timer = setInterval(() => { if (!document.hidden)refresh() }, 15000) })
onBeforeUnmount(() => { disposed = true; clearInterval(timer) })
</script>
