<template><div class="cc-live-player"><div ref="shell" class="cc-player-surface"></div><div v-if="error||!playing" class="cc-player-status"><VideoCameraOutlined /><span>{{ error||(!url?'尚无可播放视频流':'正在连接视频…') }}</span><button v-if="error" class="cc-button" @click="connect">重新连接</button></div><span v-else class="cc-live-label">实时画面</span></div></template>
<script setup lang="ts">
import { ref, watch, onMounted, onBeforeUnmount } from 'vue'
import { VideoCameraOutlined } from '@ant-design/icons-vue'
import { createVideoPlayerSlot, monitorVideoPlayer } from '/@/components/cockpit/video-bandwidth-runtime.mjs'
import { rtcPlaybackUrl } from './video-layout.mjs'
const props = defineProps<{url?:string}>(); const shell = ref<HTMLElement|null>(null); const error = ref(''); const playing = ref(false)
let disposed = false; let timer:ReturnType<typeof setTimeout>|undefined
const slot = createVideoPlayerSlot((p:any) => { p.disposed = true; p.stopMonitor?.(); p.close?.(); p.video?.remove() })
async function connect () { clearTimeout(timer); slot.clear(); playing.value = false; error.value = ''; if (!props.url || !shell.value || disposed || document.hidden) return; const value = props.url; await slot.replace(async (isCurrent:any) => { const video = document.createElement('video'); video.autoplay = true; video.muted = true; video.playsInline = true; video.style.cssText = 'width:100%;height:100%;object-fit:contain'; try { const urls = rtcPlaybackUrl(value); let client = (window as any).ZLMRTCClient; if (!client) { await new Promise<void>((resolve, reject) => { const script = document.createElement('script'); script.src = urls.script; script.async = true; const timeout = setTimeout(() => { script.remove(); reject(new Error('播放器加载超时')) }, 10000); script.onload = () => { clearTimeout(timeout); script.remove(); resolve() }; script.onerror = () => { clearTimeout(timeout); script.remove(); reject(new Error('播放器加载失败')) }; document.head.appendChild(script) }); client = (window as any).ZLMRTCClient } if (!isCurrent() || disposed) return null; if (!client?.Endpoint) throw new Error('播放器不可用'); shell.value?.replaceChildren(video); const endpoint = new client.Endpoint({ element: video, zlmsdpUrl: urls.sdp, recvOnly: true, useCamera: false, audioEnable: false, videoEnable: true }); endpoint.video = video; const mark = () => { if (!isCurrent() || endpoint.disposed) return; playing.value = true; error.value = ''; clearTimeout(timer) }; video.addEventListener('playing', mark); video.addEventListener('error', () => { if (isCurrent())error.value = '视频解码失败，请重试' }); endpoint.stopMonitor = monitorVideoPlayer(endpoint, video, (metrics:any) => { if (!isCurrent() || endpoint.disposed) return; if (metrics.stalled && playing.value) { playing.value = false; error.value = '视频画面已停滞，请重新连接' } }); timer = setTimeout(() => { if (isCurrent() && !playing.value)error.value = '视频连接超时，请检查媒体链路' }, 15000); endpoint.on?.(client.Events.WEBRTC_ON_CONNECTION_STATE_CHANGE, (state:string) => { if (isCurrent() && ['failed', 'disconnected', 'closed'].includes(state)) { playing.value = false; error.value = '视频连接中断' } }); return endpoint } catch (e) { video.remove(); if (isCurrent())error.value = '无法连接视频，请检查播放地址或媒体服务'; return null } }) }
watch(() => props.url, connect)
function visibility () { if (document.hidden) { slot.clear(); playing.value = false; clearTimeout(timer) } else connect() }
onMounted(() => { connect(); document.addEventListener('visibilitychange', visibility) })
onBeforeUnmount(() => { disposed = true; clearTimeout(timer); slot.clear(); document.removeEventListener('visibilitychange', visibility) })
</script>
<style scoped>.cc-live-player{height:100%;position:relative;background:#060c14;overflow:hidden}.cc-player-surface{height:100%;width:100%}.cc-player-status{position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:15px;color:#849cb9;padding:20px;text-align:center}.cc-player-status>.anticon{font-size:28px}.cc-live-label{position:absolute;left:12px;bottom:10px;color:#91d9b8;font-size:11px;background:#10291edb;padding:4px 7px}</style>
